GET http://94.198.50.185:7081/api/users
Accept: application/json

<> 2023-05-25T203356.200.json

###

POST http://94.198.50.185:7081/api/users
Content-Type: application/json

{
  "id": 3,
  "name": "James",
  "lastName": "Brown",
  "age": 26
}

<> 2023-05-25T203357.200.txt

###
PUT http://94.198.50.185:7081/api/users
Content-Type: application/json

{
  "id": 3,
  "name": "Thomas",
  "lastName": "Shelby",
  "age": 26
}

<> 2023-05-25T203357-1.200.txt

###
DELETE http://94.198.50.185:7081/api/users
Content-Type: application/json

<> 2023-05-25T203357.405.json
